openapi: 3.0.0
info:
  title: SS_MMetaConnectivityRequirement
  description: |
    API for SEAL Mobile MetaConnectivity Requirements.  
    © 2026, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.
  version: "1.0.0-alpha.1"

externalDocs:
  description: >
    3GPP TS 29.549 V20.1.0 Service Enabler Architecture Layer for Verticals (SEAL);
    Application Programming Interface (API) specification; Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.549/

security:
  - {}
  - oAuth2ClientCredentials: []

servers:
  - url: '{apiRoot}/ss-mmeta/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 6.5 of 3GPP TS 29.549

paths:
  /subscriptions:
    post:
      summary: Create individual unicast connectivity requirements subscription resource.
      operationId: SubscribeConnectivityRequirements
      tags:
        - Connectivity Requirements Subscriptions (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectivitySubscription'
      responses:
        '201':
          description: >
            The requested individual connectivity requirements subscription resource is
            successfully created and a representation of the created resource is returned
            in the response body.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectivitySubscription'
          headers:
            Location:
              description: Contains the URI of the newly created individual resource.
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      callbacks:
        NotifyConnectivityRequirementsData:
          '{$request.body#/notifUri}': 
            post:
              summary: >
                Notify on updates of the individual connectivity requirements resorce accoring
                the requested reporting settings.
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ConnectivityReport'
              responses:
                '204':
                  description: The notification is successfully received.
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions/{subscriptionId}:
    parameters:
      - name: subscriptionId
        in: path
        description: String identifying an individual connectivity requirements resource.
        required: true
        schema:
          type: string

    get:
      summary: Retrieve an existing individual connectivity requirements subscription resource.
      operationId: RetrieveConnectivityRequirements
      tags:
        - Individual connectivity requirements (Document)
      responses:
        '200':
          description: Individual connectivity requirements subscription is retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectivitySubscription'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    put:
      summary: Update completely an existing individual connectivity requirements subscription
        resource.
      operationId: UpdateConnectivityRequirements
      tags:
        - Individual connectivity requirements (Document)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectivitySubscription'
      responses:
        '200':
          description: >
            OK. The individual connectivity requirements subscription is completely updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectivitySubscription'
        '204':
          description: successful case but without any Content
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    patch:
      summary: Modify partially an existing Individual connectivity requirements subscription
        resource.
      operationId: ModifyPartiallyConnectivityRequirements
      tags:
        - Individual connectivity requirements (Document)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConnectivitySubscriptionPatch'
      responses:
        '200':
          description : >
            OK. The individual connectivity requirements subscription is partially modified.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectivitySubscription'
        '204':
          description: successful case but without any Content
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    delete:
      summary: Deletes an existing Individual connectivity requirements subscription resource.
      operationId: DeleteConnectivityRequirements
      tags:
        - Individual connectivity requirements (Document)
      responses:
        '204':
          description: Individual connectivity requirements subscription is deleted.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}

  schemas:
    ConnectivitySubscription:
      description: The connectivity requirements subscription request.
      type: object
      properties:
        notifUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        valServiceId:
          type: string
        mMetaPerf:
          $ref: '#/components/schemas/MMetaPerfReqs'
        valUeCapability:
          $ref: '#/components/schemas/MMetaCapReqs'
        servArea:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/LocationArea5G'
        timeValidity:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/TimeWindow'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - notifUri
        - valServiceId
        - mMetaPerf
        - valUeCapability
        - servArea

    ConnectivityReport:
      description: The connectivity requirements report.
      type: object
      properties:
        mMetaSession:
          $ref: '#/components/schemas/MMetaSessionInfo'
        valServiceId:
          type: string
        valUeIds:
          type: array
          items:
            $ref: '#/components/schemas/ConnUe'
          minItems: 0
      required:
        - mMetaSession
        - valServiceId

    ConnectivitySubscriptionPatch:
      description: The modified connectivity requirements subscription request.
      type: object
      properties:
        notifUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        mMetaPerf:
          $ref: '#/components/schemas/MMetaPerfReqs'
        valUeCapability:
          $ref: '#/components/schemas/MMetaCapReqs'
        servArea:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/LocationArea5G'
        timeValidity:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/TimeWindow'

    MMetaPerfReqs:
      description: The mobile metaverse performance requirements.
      type: object
      properties:
        mMetaQoSReq:
          type: string
        latency:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
        errorRate:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/PacketErrRate'
      required:
        - mMetaQoSReq
        - latency
        - errorRate

    MMetaCapReqs:
      description: The mobile metaverse capability requirements.
      type: object
      properties:
        valUeType:
          type: string
        usageLevel:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
      required:
        - valUeType
        - usageLevel

    MMetaSessionInfo:
      description: The mobile metaverse Session Information.
      type: object
      properties:
        sessionId:
          type: string
        sessionType:
            $ref: '#/components/schemas/MMetaSessionType'
        sessionQoS:
            $ref: '#/components/schemas/MMetaSessionQos'
      required:
        - sessionId
        - sessionType
        - sessionQoS

    MMetaSessionQos:
      description: The mobile metaverse Session QoS information.
      type: object
      properties:
        latency:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uinteger'
        jitter:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Float'
      required:
        - latency
        - jitter

    ConnUe:
      description: The selected VAL UE for the established connectivity.
      type: object
      properties:
        valUe:
          $ref: 'TS29549_SS_UserProfileRetrieval.yaml#/components/schemas/ValTargetUe'
        connectionInfo:
          $ref: 'TS29548_SDD_Transmission.yaml#/components/schemas/ConnInfo'


# Simple data types


# Enumerations

    MMetaSessionType:
      anyOf:
      - type: string
        enum:
           - UE_TO_NETWORK
           - UE_TO_UE
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration and is not used to encode
          content defined in the present version of this API.
      description: |
        Presents information about the application session for the established connectivity.  
        Possible values are:
        - UE_TO_NETWORK: Identifies the VAL application session for the established connectivity 
          is of type UE to network.
        - UE_TO_UE: Identifies the VAL application session for the established connectivity 
          is of type UE to UE.
